### ISSUE TITLE
Nearby window stops working when event is turned on as a field

### ISSUE THREAD

**Issue by Zenmaster28** [SauceLLC/sauce4zwift#103]
Issue: When event is checked in the field settings as a data field only the watched rider gets updated and the rest remain static.   Errors in the console about sg.event being undefined

Cause: the fmtEvent function is looking for sg.event.id and sg.event.name when it should be sg.id and sg.name

**Comment by mayfield** [comment]
Fixed in recent alpha builds, forgot to link back to this issue when I commited.
