### ISSUE TITLE
"Multiple Logins Detected" / sauce then frozen out

### ISSUE THREAD

**Issue by mikehardy** [SauceLLC/sauce4zwift#106]
**Describe the bug**

With apologies, I do not have the full error message that popped up in a dialog box on the screen when this happened - forgive me as it was in the middle of a race 😅 

I'll do my best to describe what happened

**To Reproduce**
1. Open zwift, get it going (windows, if it matters)
2. Open zwift companion, get it going (android, if it matters)
3. Open sauce, get it going (same windows machine the game client from 1 above was on, if that matters)
4. Enter a race, start racing, enjoy your nice sauce experience while suffering
5. A dialog popped up, perhaps 10 minutes in to the race? That had a title of "Multiple logins detected", a bunch of text which I could not read without glasses and definitely not while racing, so I clicked okay and was curious what would happen
6. about a minute later the sauce data stream froze, whatever was there just stayed there, and there were no further updates

At that point since I was in the middle of a race I just closed sauce and max-ed the zwift window and got on with the race

This appears to be some sort of new behavior though!

**Expected behavior**
Well I've been using sauce quite some time. v1.1.2 since it prompted for an update. It has been working fine.

Zwift is on 1.57.3 now, and I believe that may be the thing that changed - I'm aware they rolled back to 1.56 for a while so this may be the first time I've raced with 1.57.x + sauce, and perhaps something has changed?

**Screenshots**

Wish I'd caught one! I'll try again

**Desktop (please complete the following information):**
 - OS: windows 11, fully patched up
 - Browser: not sure it matters? brave, fully patched up and restarted though
 - Version 1.1.2 of sauce, 1.57.3 of zwift

**Additional context**

Maybe I'm the only one experiencing this? I was surprised not to see any open issues on it as it seems like sauce may have a serious problem if zwift client is detecting multiple logins now and shutting sauce down...

**Comment by mayfield** [comment]
Can confirm, something upwind changed.  Thanks @mikehardy

**Comment by mikehardy** [comment]
When I use sauce on one machine and Zwift client on another machine and they are on separate/ isolated networks, things work. I infer from that local network visibility is a component of whatever changed

**Comment by mayfield** [comment]
> When I use sauce on one machine and Zwift client on another machine and they are on separate/ isolated networks (tested today a couple times, a few hours), things work. I infer from that local network visibility is a component of whatever changed

It's part of the session refresh technique that takes place around every 85 minutes (90 min session expiration with saftey margin).

I have a good fix in the works already. :)

**Comment by mikehardy** [comment]
Hey there @mayfield 👋 I may be missing something (happens annoyingly often...) but is this released yet? I didn't think it was in v1.1.2 and I only see alphas of 1.1.3/1.1.4 ?

Should I switch to the alpha channel to get a release with this fix incorporated? Or I'm missing something and I should do the thing I'm missing

**Comment by mikehardy** [comment]
I switched to the alpha channel, it pulled down 1.1.4 and that worked
