### ISSUE TITLE
Multiple Logins Detected

### ISSUE THREAD

**Issue by hermannatorii** [SauceLLC/sauce4zwift#108]
**Describe the bug**
Multiple Logins Detected Window when using Sauce and two mods

**To Reproduce**
Open zwift, get it going (windows, if it matters)
Open zwift companion, get it going (android, if it matters)
Open sauce, get it going (same windows machine the game client from 1 above was on, if that matters)
Enter a race, start racing, enjoy your nice sauce experience while suffering
A dialog popped up, perhaps 16 minutes in to the race? That had a title of "Multiple logins detected", some of my windows in Sauce closed and others did not
This appears to be some sort of new behavior

**Expected behavior**
Used sauce quite some time. v1.1.2 since it prompted for an update. It has been working fine.

Zwift is on latest update

**Screenshots**
https://www.twitch.tv/videos/2055107694

Check pop up at 18:07 on feed
![image](https://github.com/SauceLLC/sauce4zwift/assets/122632973/6dc5a1ec-ea76-4b56-b8a2-6e14d7efbd06)

**Desktop (please complete the following information):**
OS: windows 11, fully patched up
Browser: Chrome
Version 1.1.2 of sauce, 1.57.3 of zwift

**Additional context**
https://www.twitch.tv/videos/2055107694

Check pop up at 18:07 on feed

**Comment by mayfield** [comment]
Fixed in 1.1.3-alpha  See: #106
