### ISSUE TITLE
in a race, sauce will not pull any data or show anything other than an empty world map

### ISSUE THREAD

**Issue by KimonLHi** [SauceLLC/sauce4zwift#120]
With the latest zwift academy race event, no data appeared in zwift sauce. as soon as the race ended, data started to populate into the widgets.

**To Reproduce**
1. join a zwift academy race
2. note an absence of data
3. leave the race or start a different ride and observe the reappearance of data

linux with zwift running on an ipad on the same network

i wonder if this may be a ZADA intervention/block if extra drafting etc information from sauce might be perceived as an unfair advantage?

**Comment by mayfield** [comment]
I think those races include a tag that tells Sauce to turn off.
