### ISSUE TITLE
Chat not working anymore (during grouprides)

### ISSUE THREAD

**Issue by huysp** [SauceLLC/sauce4zwift#123]
Hi,

The last 10 days or so the Chat window of Zwift Sauce is not longer showing the chats. 
I have the  feeling is mostly occuring with grouprides. 
When riding with a pace partner it seems to be working 

This kinda ruins my ride  because I chat a lot.
The alternative is Zwift Companion app but that is mostly not working. It's not seeing i'm riding so ... 

Hope this problem can be fixed quickly.

**Comment by LTZGH** [comment]
I posted the same issue: https://github.com/SauceLLC/sauce4zwift/issues/122

**Comment by LTZGH** [comment]
Thank you🤟

**Comment by huysp** [comment]
Will give it a test tomorrow tuesday or wednesday. Thank you
