### ISSUE TITLE
New Routes Map Profiles

### ISSUE THREAD

**Issue by LeebZHCC** [SauceLLC/sauce4zwift#126]
Do we know when the profile on the map will start to display the new routes?  Im getting no profiles when riding many of the new routes introduced over the last few months.  Im running 1.1.6.

Thanks
Lee

**Comment by Zenmaster28** [comment]
@LeebZHCC if you update your update channel to Alpha in the sauce settings, you will get a newer version that includes the new routes and maps.

**Comment by LeebZHCC** [comment]
Thank you, forgive me but I cant seem to see how to do this in my Sauce settings?

Regards
Lee

________________________________

**Comment by LeebZHCC** [comment]
Its ok sorted - thank you

________________________________
