### ISSUE TITLE
When switching themes the settings window doesn't refresh to new theme

### ISSUE THREAD

**Issue by AradRoy** [SauceLLC/sauce4zwift#21]
Hi there amazing Justin 

Just noticed a tiny bug. When I change theme all open windows and gauges change to the new theme except the big settings window in which I selected the new theme. If I close and reopen the settings window, it does updates to the new theme. 

It's the most tiny and least important bug but I thought I'll just let you know :)
Thank you for the AWESOME work!

**Comment by mayfield** [comment]
Hi @AradRoy Already fixed in the upcoming release. :smile:
