### ISSUE TITLE
elevation map

### ISSUE THREAD

**Issue by gtdean11** [SauceLLC/sauce4zwift#27]
Would like an elevation map that is better than zwifts pitiful default. Ideas:

Shows the route you're actually on (instead of random segments).

Gives some sense of distance

Always goes left to right

Extra decimal place on current elevation.

Something readable that tells you how steep the path ahead is

Randomly adds hills when username = serkit

**Comment by mayfield** [comment]
That last function is by far the most important!

**Comment by Jason-The-Shepherd** [comment]
RGT (now Wahoo RGT) provide two elevation profiles and one top down route map. I like the way they have done it. Each can be turned off if not required/desired although position and size can't be changed.

One of the elevation profiles resides in the distance and elevation window and shows detailed elevation (terrain and % gradient) several hundred metres ahead as well as other riders (as dots) on that section of road. The other is similar to Rouvy and sits at the bottom of the screen, is full screen width and shows gradient with colour as well as position of all riders (as dots) on the route.

**Comment by doublejj0321** [comment]
This would be a great addition... I like to ride "hubless" but like to anticipate a climb using the default map in the top right

**Comment by Zombi3666** [comment]
Would love to see something like this!

**Comment by oldnapalm** [comment]
I guess you already know, but just in case, route data can be obtained from file Zwift\assets\Worlds\worldX\data_1.wad\Worlds\worldX\routes\routesX.xml (highrescheckpoint or checkpoint)

**Comment by mayfield** [comment]
Thanks @oldnapalm I might use the route checkpoint data for events where that info is present.  In dev I've been using the similar road.xml checkpoint data and it's working nicely so far.

**Comment by mayfield** [comment]
completed (mostly); please file a new issue for any missing features.
