### ISSUE TITLE
Windows link-state loss can cause hard crash in node

### ISSUE THREAD

**Issue by ruffk** [SauceLLC/sauce4zwift#3]
Riding today my network dropped for about 1-2 seconds.  The Sauce windows all closed losing my metrics.  Might it be possible to recover from this as it can be a common occurrence for some users?  Thanks.

**Comment by mayfield** [comment]
It should recover on it's own, so sounds like something very unexpected happened.  Can you email me logs from this session possibly?  support@saucellc.io

**Comment by ruffk** [comment]
Hi, so for the last three sessions I've raced with Sauce and in each I had a short network blip.  Zwift recovered but Sauce disappeared.  
[sauce.log](https://github.com/SauceLLC/sauce4zwift/files/9753527/sauce.log)
[sauce1.log](https://github.com/SauceLLC/sauce4zwift/files/9753547/sauce1.log)

**Comment by mayfield** [comment]
Hi @ruffk `sauce.1.log` looks like an upgrade from **0.10.6** to **0.10.9** and then the `sauce.log` file is session right after that upgrade 3:48 to 4:47 (your local time).  Can you confirm this was the session where Sauce wedged?  I combed through it, but it actually looks like the network connection was working for that entire hour without interruption.

Another question, when you say all the windows closed, does that include the main top bar?  And where there any other error dialogs present during the interruption?

**Comment by ruffk** [comment]
Hi
0447 was when Sauce terminated and all windows closed, including the main bar. Network wise I was seeing the rider list essentially shrink to only me for a second or two. It was during ZRL this morning.

Regards,

Kevin

________________________________

**Comment by mayfield** [comment]
Oh interesting.  So Sauce hard crashed.  I think the log file didn't even have a chance to flush.

**Comment by ruffk** [comment]
Hi, had another crash today during ZRL.  Updated to latest version prior.  Ran for about 30 min, then it seems network blipped, rider list disappeared for a couple seconds.  Attached is log.

[sauce.log](https://github.com/SauceLLC/sauce4zwift/files/9960642/sauce.log)

**Comment by mayfield** [comment]
Able to crash with Win10 VM and link state toggled off.

```
..\..\third_party\electron_node\src\stream_base.cc:590: Assertion `(buf.base) == (buffer_.base)' failed.
 1: 00007FF7EA50F706 node::Buffer::New+47862
 2: 00007FF7EA50F44C node::Buffer::New+47164
 3: 00007FF7EB1F5F0B node::CommonEnvironmentSetup::context+13035
 4: 00007FF7EABC522B uv_dlerror+638619
 5: 00007FF7EABC5A01 uv_dlerror+640625
 6: 00007FF7EAC24092 uv_tcp_getpeername+1474
 7: 00007FF7EA5237E3 uv_run+451
 8: 00007FF7E89594AC node::FreePlatform+21820
 9: 00007FF7EC2F4038 cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow+3391416
10: 00007FF7EC39AA1E cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow+4073886
11: 00007FF7EC300A2B cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow+3443115
12: 00007FF7E9F74755 node::GetEnvironmentIsolateData+9132213
13: 00007FF7EA53F1E5 uv_sleep+95285
14: 00007FF7E9F48C1E node::GetEnvironmentIsolateData+8953214
15: 00007FF7E97C2E02 node::GetEnvironmentIsolateData+1064802
16: 00007FF7E97C4B21 node::GetEnvironmentIsolateData+1072257
17: 00007FF7E97C0229 node::GetEnvironmentIsolateData+1053577
18: 00007FF7E8A6432F v8::metrics::LongTaskStats::LongTaskStats+519983
19: 00007FF7E8A659F0 v8::metrics::LongTaskStats::LongTaskStats+525808
20: 00007FF7E8A65398 v8::metrics::LongTaskStats::LongTaskStats+524184
21: 00007FF7E8A617B0 v8::metrics::LongTaskStats::LongTaskStats+508848
22: 00007FF7E8A618EF v8::metrics::LongTaskStats::LongTaskStats+509167
23: 00007FF7E87DD0D1 std::Cr::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame> >::vector<v8::CpuProfileDeoptFrame,std::Cr::allocator<v8::CpuProfileDeoptFrame> >+63809
24: 00007FF7EC6535C2 cppgc::internal::WriteBarrier::DijkstraMarkingBarrierRangeSlow+6927682
25: 00007FFDC8B87974 BaseThreadInitThunk+20
26: 00007FFDC9CCA2F1 RtlUserThreadStart+33
```
