### ISSUE TITLE
Some suggestions for metrics displayed

### ISSUE THREAD

**Issue by ruffk** [SauceLLC/sauce4zwift#4]
In the Power graph

- When using a rolling collector (such as 20 min), allow to change the units displayed from Watts to W/Kg.
- Add an additional rolling collector based upon the 20 min (max) to display 95% of the value, preferably in W/Kg.  A typical FTP calculation.

Would it be possible to have a selection for a transparent background on widgets so that they don't block Zwift's own values?

Overall, a really good experience using the tool today.  Thanks Justin!

**Comment by Helioth** [comment]
Following on this, most interesting rolling collector metrics are available in the main app task bar. The way it is now, it is not straightforward to visualize all interesting metrics. Why not having a new screen to allow to display them (max and current values for 15s, 1', 2', 5', 10', 20', 30', 60', avg, for power in w and w/kg, HR as well as FTP predictor for time intervals above 10 minutes). A bit like in Zwift Activity Monitor.

**Comment by Jason-The-Shepherd** [comment]
Is it possible to show the most common value (mode) for a given time period in addition to the average. My intention would be to know at what power/HR/cadence (any metric) I am spending most of my time during a session.

**Comment by mayfield** [comment]
Hi I'm closing this as I think I have addressed the majority of the original issue, @Jason-The-Shepherd and @Helioth can you file a separate issues so I can burn them down individually.  I'll loose track of the specific requests otherwise or not be able to close out issues ever.
