### ISSUE TITLE
Average power seems incorrect

### ISSUE THREAD

**Issue by ChillyWilly-the-cyclist** [SauceLLC/sauce4zwift#49]
Forgive me as I'm only a week into this, but im loving the additional data!  
My only issue has been that average power has been very low on each ride.  Actual power is accurate but average is crazy low.  Is sauce averaging time at zero power into the number?  I.e. if I start sauce before I start zwift, then it takes me 10 minutes to start a course or to even just start riding after I entered a course, does that 10 min of zero now count?  Its the only plausible reason I can imagine.  So the fix would be to only start sauce after I've begun the ride. Correct?  If that is true, it would be nice to drop out those zeroes.  Anyhow, just wanted to ask.  Thank you!

**Comment by mayfield** [comment]
Hi @ChillyWilly-the-cyclist 

Auto-pause isn't implemented yet, so you're seeing elapsed power averages.  I'm working on this and will update #5 when it's ready.  I'll close this so I only have one issue to track.

Thank you.

**Comment by ruffk** [comment]
Zeros cannot be dropped on power collection (think about going downhill). Having a pause and auto start feature has been raised in another issue.

Regards,

Kevin

On Oct 30, 2022, at 1:26 PM, ChillyWilly-the-cyclist ***@***.***> wrote:

﻿

Forgive me as I'm only a week into this, but im loving the additional data!
My only issue has been that average power has been very low on each ride. Actual power is accurate but average is crazy low. Is sauce averaging time at zero power into the number? I.e. if I start sauce before I start zwift, then it takes me 10 minutes to start a course or to even just start riding after I entered a course, does that 10 min of zero now count? Its the only plausible reason I can imagine. So the fix would be to only start sauce after I've begun the ride. Correct? If that is true, it would be nice to drop out those zeroes. Anyhow, just wanted to ask. Thank you!
