### ISSUE TITLE
Add optional auto-pause option

### ISSUE THREAD

**Issue by ruffk** [SauceLLC/sauce4zwift#5]
Currently, once Sauce starts, the collectors for rolling averages start too.  To make the app a bit more rider friendly, I suggest an auto-pause option.

If auto-pause is enabled, the Sauce timer would:
- Begin counting when
   - Rider motion is detected (i.e. the Avatar begins pedaling)
   - The Zwift clock is running
- Stop counting when
   - Rider motion ceases (i.e. the Avatar stops)

This feature is nice for two reasons:
1. When in the event pen, you could reset Sauce and it won't start until the event starts (rider moves) and the event clock starts (usually after pen exit).
2. If you need to step off the bike the counters will stop too.

**Comment by mayfield** [comment]
I have plans to do something similar to this with event related auto lapping or reseting.  But I like the idea of auto pause in general too.

**Comment by pelleoss** [comment]
A TIMER (to be set manually) would be simple and fast solution for events. Souce would start to collect statistics at the end of the timer.

**Comment by mayfield** [comment]
Cross referencing this: #30

**Comment by mayfield** [comment]
Completed, will be in next release.  No option, the system will always use active time instead of elapsed.
