### ISSUE TITLE
Sauce shuts down during a wireless reconnection

### ISSUE THREAD

**Issue by Helioth** [SauceLLC/sauce4zwift#58]
Using a wireless connection, the Sauce crashes (shuts down) when getting disconnected from the network. This may happen quite often when the wireless network is a bit unstable. On Zwift, during a network reconnection, the other riders just disappear for a few seconds.

The Sauce should instead be able to resume after a wireless reconnection, without shutting down and resetting all stats.

**Comment by mayfield** [comment]
@Helioth closing in favor of #3

Real quick can you confirm that this is on Windows and which version of windows you are using?
