### ISSUE TITLE
Sauce for Zwift seems to stops Companion app from syncing with Zwift

### ISSUE THREAD

**Issue by matty-boy79** [SauceLLC/sauce4zwift#59]
Please refer to Zwift support thread: https://forums.zwift.com/t/zwift-companion-app-on-ios16-wont-connect-september-2022/590173/114?u=mattw
Seems that if Sauce is running before Zwift, the CA will not 'sync' with Zwift running on PC (and maybe other platforms).
If I close Sauce, CA starts syncing within seconds. I can then start Sauce and they both work fine.
So there is a workaround of making sure Zwift is running before Sauce is opened.
The Companion app issue is seen on iPhones running iOS 16.x when Sauce is running before Zwift starts.

**Comment by BasWeg** [comment]
Have you enabled "Game Connection" in sauce for zwift?

**Comment by matty-boy79** [comment]
Hi,
I'm not sure without going out to the garage to check. Could this setting
cause the issue I'm seeing? Should I have it enabled or disabled do you
think?
Thanks!

**Comment by BasWeg** [comment]
With "Game Connection" enabled, sauce behaves like the companion app, so you can give ride ons, fan view other riders etc.
But their can only be one companion app. So, in my opinion if you want to use the companion app it should be disabled.

**Comment by matty-boy79** [comment]
OK, cool, thank you. I will check and let you know.

**Comment by matty-boy79** [comment]
You were absolutely right. I'm so sorry for wasting your time! Please feel
free to close the issue off as "User Error - Didn't RTFM" :)
