### ISSUE TITLE
lost all presets when updating yesterday

### ISSUE THREAD

**Issue by LeebZHCC** [SauceLLC/sauce4zwift#77]
Love S4Z but the last time I updated it lost all my windows and data settings so had to set them all up again. Yesterday I updated as I could see that we will now have a map and gradient, elevation etc (super chuffed for that) . Updated and every data field was "elapsed time" so had to reset them all again.

Now knowing I may lose my settings when updating S4Z I downloaded my settings before updating. After the update and all settings lost, I installed my saved settings but that didn't change anything? Am I doing something wrong?

**Comment by LeebZHCC** [comment]
Hi Justin

These ones?

Regards
Lee

**Comment by LeebZHCC** [comment]
Hi Justin Just to add that Jason my riding buddy experienced the same yesterday when updating. The layout of everything was the same, even the draft dials etc but all the fields defaulted to “elapsed time” on the primary data bar RegardsLee Sent from Mail for Windows From: Justin MayfieldSent: 04 April 2023 20:52To: SauceLLC/sauce4zwiftCc: LeebZHCC; MentionSubject: Re: [SauceLLC/sauce4zwift] lost all presets when updating yesterday (Issue #77) Hi @LeebZHCC you definitely should not lose your settings. Can you email the sauce.log* files from the AppData/Roaming|Local/Sauce for ZwiftTM/ folder?—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by Helioth** [comment]
Happens to me as well in the overview window every time a new data field is made available.

**Comment by mayfield** [comment]
Fixed in 0471183095cf3c7b2f96d1c6bade58a0280859a9
