### ISSUE TITLE
Data tables on new minimap very hard to read

### ISSUE THREAD

**Issue by LeebZHCC** [SauceLLC/sauce4zwift#78]
Fantastic to have the new minimap on the SFZ but when adding data tables (I have added "gradient" and "climbed") they are in black text on a dark background which is really quite hard to see/read.  Could we have a lighter background with black text or dark background with white text.  Either will do just as long as its easier to read.

Thx
Lee

**Comment by LeebZHCC** [comment]
Thanks for this Justin, do I need to wait for the next release before the changes will take place? RegardsLee Sent from Mail for Windows From: Justin MayfieldSent: 06 April 2023 22:11To: SauceLLC/sauce4zwiftCc: LeebZHCC; AuthorSubject: Re: [SauceLLC/sauce4zwift] Data tables on new minimap very hard to read (Issue #78) Closed #78 as completed via fb85933.—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>

**Comment by mayfield** [comment]
@LeebZHCC Yeah it will be in v0.13.1

**Comment by LeebZHCC** [comment]
Brilliant – what you are providing to us Zwifters is just brilliant, so much better than the oem HUD.  Makes leading rides and monitoring average pace super easy and if you are a data freak then the world is your oyster.  Thoroughly appreciated Justin -Thank you 😊  Sent from Mail for Windows From: Justin MayfieldSent: 06 April 2023 22:26To: SauceLLC/sauce4zwiftCc: LeebZHCC; MentionSubject: Re: [SauceLLC/sauce4zwift] Data tables on new minimap very hard to read (Issue ***@***.*** Yeah it will be in v0.13.1—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>

**Comment by mayfield** [comment]
Thanks @LeebZHCC! Cheers!
