### ISSUE TITLE
Latency monitor

### ISSUE THREAD

**Issue by PerBacks** [SauceLLC/sauce4zwift#85]
**Strange Latency numbers**
 Hi, discovered that i can monitor my zwift latency but it puzzles me a bit.

When i do latency check with AWS latency test i get approx 240ms roundtrip. (Sweden/Stockholm to aws Oregon)

When i do latency check with Zwiftalizer I get approx 170ms latency roundtrip

In S4Z, in race i get some 43ms which is very low vs what I get from AWS and Zwiftalizer. How/why is this number so low?

Also, sometimes the latency get negative number like -4ms, -12ms, what does that mean when my latency becomes negative?

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**

**Additional context**

**Comment by mayfield** [comment]
Thanks for the report.

Looks like my SNTP algo had the sign wrong on latency offset when setting the worldtime clock.
