### ISSUE TITLE
Rider goes right to left on elevation map after U-turn

### ISSUE THREAD

**Issue by gtdean11** [SauceLLC/sauce4zwift#91]
**Describe the bug**
After U-Turning the rider pin goes right to left instead of left to right.

**To Reproduce**
1. Go to any route
2. U-turn

**Expected behavior**
Elevation map at the bottom should flip horizontally so rider goes left to right.

**Screenshots**
https://youtu.be/9FnH1ydpxVs

**Desktop (please complete the following information):**
 - OS: Windows

**Additional context**
Running on Alpha

**Comment by mayfield** [comment]
I think I fixed this already.  The change is in the, just released, 0.99.7 build.  Can you reopen this if you see this behavior again?

**Comment by gtdean11** [comment]
fixed.  Thanks!
