### ISSUE TITLE
Time difference calculation between groups is wrong

### ISSUE THREAD

**Issue by trust123500** [SauceLLC/sauce4zwift#92]
**Describe the bug**
Time difference calculation between groups is wrong. 
<img width="288" alt="image" src="https://github.com/SauceLLC/sauce4zwift/assets/15710429/17496055-365c-41d5-9292-85bcae95c914">

As you can see, the time difference between M.Murray and G.Rison should be 17s instead of 32s.

The difference between G.Rison and B.l Gorillaz should be 9s instead of 18s

**To Reproduce**
Go to a race and compare the time differences on the Sauce 4 Zwift and Zwift Leaderboard

**Expected behavior**

The time difference calculation should match the official Zwift one

**Desktop (please complete the following information):**
 - OS: MacOS

**Comment by BasWeg** [comment]
Not really. Zwift use a fixed speed for calculating the time gap. This does not fit in any case. 
Sauce provides more realistic data based on actual speed. As far as I know and recognized it during races.
