### ISSUE TITLE
Map

### ISSUE THREAD

**Issue by Afnug** [SauceLLC/sauce4zwift#95]
The new routes in Zwift, do not appear on the Sauce Map

**To Reproduce**
Open the Sauce and ride some of the new coastal routes.

**Expected behavior**
I expected the map to scroll along the new routes.

**Screenshots**

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 

**Additional context**

**Comment by mayfield** [comment]
Hi @Afnug these are in the alpha and beta builds now.  I have to roll a new release anytime new road data is included.

You can install a beta or alpha build now from here:
https://github.com/SauceLLC/sauce4zwift-releases/releases

**Comment by Afnug** [comment]
Thanks for the quick reply and info, enjoying all the data.


Steve
