### ISSUE TITLE
Browser source settings URL doesn't seem to do anything

### ISSUE THREAD

**Issue by gtdean11** [SauceLLC/sauce4zwift#98]
**Describe the bug**
Browser source settings URL doesn't seem to do anything

**To Reproduce**
Enter URL in browser source settings

**Expected behavior**
Goes to URL

**Desktop (please complete the following information):**
Windows 10

**Additional context**
Works if you enter in the url bar in the top of the window itself.

**Comment by mayfield** [comment]
I think the issue is that I don't auto reload the main browser-source window automatically to avoid spurious loads of incomplete urls.  If you reload the window though it will use the URL put into the settings page.

**Comment by mayfield** [comment]
Yeah, I can improve it.
